---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitlab-keycloak-oauth2
  namespace: gitlab
spec:
  encryptedData:
    provider: AgBuJ1+CBOOse4LxEHCJrRRqodf2nkSHOVYIsHBLUJggN8MoM34aHqGhAFrrxrgJeow5QMvrhXCxmP+n1+JfzvwIvc9Cbv0nNQUWeh41UwM1MV1v1UPDmqlXHBIzVtbJFcooACn4oUlaCLioApYlNSA2B5KP+y376TuBB/TuYSCiZ8GamHQcQhz3SnAXhkY1nwUXs8WQVx62NCSj3uUFk+TnoQYEz+AFVmHR3WPP2e2pec408D7gaOI6bkE3EgnV3f/lkiV7KXTdbjdLb/51kQZgZiTKM+1cWXAMl41JeKhu8vH1wiPqtpxWCHEY6yX6GwWVrY3qHYdy8VLS949ZQHIQUMZL7bvujAWIeMZQwNaFYRygI38JMGuwJTFT3kpeVO4+I9niRk1/dBSqJXXdaZHPGXldPHtbNwX1Pg6sGf/6dencam0u8sM73nisLVAK8lGF0jX7rlWaCLcQ+YiZHcpN+N0nQDhr0eKHsCTi1O/bPcoGtw5+c3cFKRLHp1wCM6/SE46b+Ry9nQClCE+n4pz+BMe88JiyKcSRbiQn4j5v8z20HK2vKrLdujGPBkgH8qTrOYYBMtms0lEdgwwAMBOzlbTSkrmSut6W69zGGDkiex+2qjmKOO8qfbjviTdtHdGBuEm4UGbdZWtS+1lZWjtEiTw0oIIGsZqa2F4ob+ah9npewU4NpaoV1EFe3r6i9c7qbyVibYLHq9aVDDwrBRn6GTCPcDysksqGgkLloqs6Q5ZPWjWS2nZxrb9ktOzkGj6EFeh+Nxa+cXusFr9yudokjmOXOZFj2BnZyhXf7vRnQyfkLYkNassD4SnSf5IQQKcZ1otn1TK7j/t5CFBKX/kr1nKQqEp2Ea8bf6QVScj0smFab3jezUOnWeyM8YKFeUJyNntrPjR6LAyVnSX1D9Sgw6Lad+h03uoZPZpgwKzhatgFmEtd5md8u5Ssl75FlR+fIuTKRQKswfiAG3hQkgmo8YSOvevyzVsbQuwc+ILjV94Fg4IQTNNfq3nqro/zVcMZSIe1dHOCevmEkzsGselR7HbAPdPcGAq5w4q0Wwf5omhmGOuNbkgH2kJkxa8+qkl5WmkREzqpFQb4tKLRjEV64P7Vnz5kfb3/YhPKdNwpNIumK4QHAE4w4OZ3E46ri4DqBd1kS7aX8eqj/g6Y/yPICwgwQS10gslK9B4EZHO9gmbkfELZaTGmd/AHzYjtsdZLaGl26YFDbe+igY7/mf5KmsqWFI+x0tIMMVFLuPe6ohgUvSM6P6hcGBLJ1i+ESBEQAidPG8sP+AGS9hVQoH5VRqLeEdPmwWxvvR1uZ+kuPHOekMli
  template:
    metadata:
      creationTimestamp: null
      name: gitlab-keycloak-oauth2
      namespace: gitlab