global:
  hosts:
    domain: home.dornol.dev
    gitlab:
      name: git.home.dornol.dev
      https: true
    registry:
      name: registry.git.home.dornol.dev
      https: true
    minio:
      name: minio.git.home.dornol.dev
      https: true
    kas:
      name: kas.git.home.dornol.dev
      https: true
  ingress:
    enabled: true
    configureCertmanager: false
    provider: traefik
    class: traefik
    tls:
      enabled: false
    annotations:
      traefik.ingress.kubernetes.io/router.tls: "true"
      traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
  shell:
    port: 2222

  gitlab-shell:
    traefik:
      entrypoint: "gitlab-shell"

  appConfig:
    omniauth:
      enabled: true
      autoLinkUser: ['openid_connect']
      allowSingleSignOn: ['openid_connect']
      blockAutoCreatedUsers: false
      providers:
        - secret: gitlab-keycloak-oauth2

nginx-ingress:
  enabled: false

gitlab-runner:
  install: true
  rbac:
    create: true
  runners:
    image: docker:24.0.2
    privileged: true
    tags: ["docker"]
    executor: kubernetes
  podAnnotations:
    gitlab.com/prometheus_scrape: "true"
    gitlab.com/prometheus_port: 9252
  podSecurityContext:
    seccompProfile:
      type: "RuntimeDefault"


installCertmanager: false