apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: outline
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      namespace: outline
      name: postgres
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_DB
              value: "outline"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: database-data
      volumes:
        - name: database-data
          persistentVolumeClaim:
            claimName: database-data

---
apiVersion: v1
kind: Service
metadata:
  namespace: outline
  name: postgres
spec:
  ports:
    - port: 5432
  selector:
    app: postgres


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: outline
  name: database-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi