apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: outline
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      namespace: outline
      name: redis
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis


---
apiVersion: v1
kind: Service
metadata:
  namespace: outline
  name: redis
spec:
  ports:
    - port: 6379
  selector:
    app: redis